<?php

namespace Console\Libraries;

use Mix\Concurrent\CoroutinePool\AbstractWorker;
use Mix\Concurrent\CoroutinePool\WorkerInterface;

/**
 * Class StockInfoCoroutinePoolWorker
 * @package Console\Libraries
 * @author alex <alexgaozhongze@gmail.com>
 */
class StockInfoCoroutinePoolWorker extends AbstractWorker implements WorkerInterface
{

    /**
     * 初始化事件
     */
    public function onInitialize()
    {
        parent::onInitialize(); // TODO: Change the autogenerated stub
        // 实例化一些需重用的对象
        // ...
    }

    /**
     * 处理
     * @param $data
     */
    public function handle($code)
    {
        $fp = fsockopen("50.push2.eastmoney.com",80, $errno, $errstr, 10) or die("$errstr ($errno)<br />\n");     
        $out = "GET /api/qt/stock/sse?ut=fa5fd1943c7b386f172d6893dbfba10b&fltt=2&fields=f43,f57,f58,f169,f170,f46,f44,f51,f168,f47,f164,f116,f60,f45,f52,f50,f48,f167,f117,f71,f161,f49,f530,f135,f136,f137,f138,f139,f141,f142,f144,f145,f147,f148,f140,f143,f146,f149,f55,f62,f162,f92,f173,f104,f105,f84,f85,f183,f184,f185,f186,f187,f188,f189,f190,f191,f192,f206,f207,f208,f209,f210,f211,f212,f213,f214,f215,f86,f107,f111,f86,f177,f78,f110,f262,f263,f264,f267,f268,f250,f251,f252,f253,f254,f255,f256,f257,f258,f266,f269,f270,f271,f273,f274,f275&secid=0.$code HTTP/1.1\r\n";     
        $out .= "Host: 50.push2.eastmoney.com\r\n";     
        $out .= "Connection: Close\r\n\r\n";     
          
        fwrite($fp, $out);     
        while (!feof($fp)) {     
            $res = fgets($fp, 128);     
            var_dump($res);
        }     
        fclose($fp);     
    }

}
